name: Android APK Uretici

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Buildozer ile APK Uret
        uses: digreatbrian/buildozer-action@v2

      - name: APK'yi Yukle
        uses: actions/upload-artifact@v4
        with:
          name: Bilgi_Labirenti_APK
          path: bin/*.apk
